['Black_flying_machine.png',
 'burning-763398.png',
 'deco_bush_square01.png',
 'deco_bush_square02.png',
 'deco_irongate01.png',
 'deco_stone_big01.png',
 'deco_stone_big02.png',
 'deco_stone_small01.png',
 'deco_stone_small02.png',
 'deco_tree_pine01.png',
 'deco_tree_pine02.png',
 'dirt_tile_01.png',
 'Fighter black.png',
 'Fighter red.png',
 'grass_tile_01.png',
 'grassdirt_cornerconc01.png',
 'grassdirt_cornerconc02.png',
 'grassdirt_cornerconc03.png',
 'grassdirt_cornerconc04.png',
 'grassdirt_cornerconv01.png',
 'grassdirt_cornerconv02.png',
 'grassdirt_cornerconv03.png',
 'grassdirt_cornerconv04.png',
 'grassdirt_sidetrans01.png',
 'grassdirt_sidetrans02.png',
 'grassdirt_sidetrans03.png',
 'grassdirt_sidetrans04.png',
 'Hollowbody 1.gif',
 'Hollowbody 2.gif',
 'Hollowbody 3.gif',
 'Hollowbody 4.gif',
 'Hollowbody 5.gif',
 'Hollowbody 6.gif',
 'human_wall_autotile2.png',
 'orc_wall_autotile2.png',
 'pave_tile_01.png',
 'pave_tile_02.png',
 'pave_tile_03.png',
 'pave_tile_04.png',
 'pave_tile_05.png',
 'pavedirt_cornerconc01.png',
 'pavedirt_cornerconc02.png',
 'pavedirt_cornerconc03.png',
 'pavedirt_cornerconc04.png',
 'pavedirt_cornerconv01.png',
 'pavedirt_cornerconv02.png',
 'pavedirt_cornerconv03.png',
 'pavedirt_cornerconv04.png',
 'pavedirt_sidetrans01.png',
 'pavedirt_sidetrans02.png',
 'pavedirt_sidetrans03.png',
 'pavedirt_sidetrans04.png',
 'sprite_monster01.png',
 'war2_grass_to_dirt_autotile.png',
 'war2_mtns_autotile.png',
 'war2_trees_autotile.png',
 'water1-animated.PNG',
 'water_to_dirt_autotile-animated.PNG',
 'whatever_to_dirt_autotile copy.png',
 'woodpanels_tile01.png',
 'woodpanels_tile02.png',
 'woodpanels_tile03.png',
 'woodpanels_tile04.png',
 'woodpanels_tile05.png',
 'woodpanels_tile06.png']
